---
title: "Лабораторная работа 1, задание 2"
output: html_notebook
editor_options: 
  markdown: 
    wrap: 72
---

### Задание 2.

Файл с данными lab1_e2.Rdata. Допустим, в рамках некоторого медицинского
исследования тестировалась эффективность новой вакцины от вируса гриппа.
Одной из целей исследования являлось изучить динамику температуры тела
пациентов на протяжении недели после вакцинации. Пациенты должны были
каждый день приходить на осмо тр, где у них измеряли температуру. Каждый
из семи дней экспериментатор вносил в таблицу id пациента и его
температуру. После окончания исследования выяснилось, что некоторые
пациенты не смогли посетить все семь приемов. Кто - то после первого
раза больше не приходил на обследование, кто - то пропустил некоторые
дни и т.д. Для чистоты исследования врачам необходимо отобрать из всех
пациентов только тех, кто посетили каждый из семи приемов. Все данные
хранятся в следующем формате: в списке all_data сохранены се мь
датафреймов, с двумя колонками:

1.  id - закодированное имя пациента
2.  temp - значения температуры.

Ваша задача написать функцию get_id, которая получает на вход такого
рода список, состоящий из семи датафрэймов. Функция, должна вернуть
новый датаф рэйм, в котором будут две переменные id и mean_temp -
среднее значение температуры за неделю только тех пациентов, которые
посетили все семь приемов, то есть id таких пациентов присутствует в
каждом из семи датафреймов.

```{r warning=FALSE}
get_id <- function(input_data) {
  merged <- Reduce(function(id, temp) merge(id, temp, by = 'id'), input_data)
  output_data <- data.frame(
    id = merged[which(colnames(merged) == 'id')],
    mean_temp = rowMeans(merged[-which(colnames(merged) == 'id')])
  )
  return(output_data)
}

setwd(getwd())

data <- load('data/lab1_e2.Rdata')
new_data <- get_id(all_data)
write.csv(new_data, "data/lab1_e2_result.csv")
```
